version: '3'
services:
  app:
    build: .
    ports:
      - "8502:8501"
    volumes:
      - .:/app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch  
    depends_on:
      - elasticsearch  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
